### PR TITLE
Remove shared buffer svprintf function and replace it with an AmxStringFormatter class

### PR DESCRIPTION
**Pull request by Hual**
Let people override server rules, fixing #647

### CODE REVIEW

**Comment by Y-Less** [comment]
The custom rules fix is fine, no issues there.

Replacing the shared string buffer with separate ones is also a good thing in theory, but I'm concerned about the effects of allocating and initialising a new 8192 element array in every native involving strings.  There's no way that two different pawn functions with this formatting can be called at the same time, the re-entrant functions like `CallLocalFunction` aren't formatted so they could be left as a shared buffer - either just the old code or a pawn-component-wide `AmxStringFormatter` instance. Alternatively `query->addRule` already makes a full copy of the strings, so having the buffers separate shouldn't contribute directly to this fix and so could be moved to a separate PR.

**Comment by Y-Less** [comment]
If the formatting were moved to a separate PR it would be good if the new buffer were expandable, removing the length checks entirely.  And then a shared buffer would slowly grow to the largest string ever seen anywhere in a script.

**Comment by Hual** [comment]
> The custom rules fix is fine, no issues there.
> 
> Replacing the shared string buffer with separate ones is also a good thing in theory, but I'm concerned about the effects of allocating and initialising a new 8192 element array in every native involving strings. There's no way that two different pawn functions with this formatting can be called at the same time, the re-entrant functions like `CallLocalFunction` aren't formatted so they could be left as a shared buffer - either just the old code or a pawn-component-wide `AmxStringFormatter` instance. Alternatively `query->addRule` already makes a full copy of the strings, so having the buffers separate shouldn't contribute directly to this fix and so could be moved to a separate PR.

Neither allocation nor initialization happens with static arrays, it would perform exactly the same

**Comment by Y-Less** [comment]
Ok you're right about the initialisation, but the class is over 8kb.  It isn't dynamic allocation, but it's still a lot of stack every time.  However, without the initialisation overhead this is much less of a problem.

**Review by Y-Less — APPROVED** [review]

**Pull request closed without merging**
