### PR TITLE
Change gravity type to float

### PR DESCRIPTION
**Pull request by vedran77**
#829

### CODE REVIEW

**Comment by shierru** [comment]
The fact that the data type is wrong is correct, but the fact that you fixed it with a number (0.008) is wrong. I already mentioned in the Issue that there is a parameter `game.gravity` in **config.json** and it should be the default value.

I think the main problem lies in the data type, which was set incorrectly, because of which the `GetPlayerGravity()` function returned an incorrect value .

**Comment by vedran77** [comment]
Thank you for your feedback. Regarding the instances where I used 0.008f in the code, please note that these values are not intended for actual use; rather, they are included solely for resetting player variables.

The default value (specified in config.json) will be applied each time a player is initialized. You can find the relevant implementation here: [link to the code](https://github.com/openmultiplayer/open.mp/blob/master/Server/Source/core_impl.hpp#L1164).

**Comment by shierru** [comment]
In my opinion it is better to use `0.0` than `0.008`, because then `0.008` becomes a "magic number" and it requires an additional declaration of it as a constant.

**Comment by vedran77** [comment]
You are probably right; the only reason I set it to 0.008 is because I saw in the documentation that the default value is 0.008. However, upon further consideration, it makes sense for it to be 0.0.

**Comment by Y-Less** [comment]
@shierru is correct about using the config value.  As it stands now calling `GetPlayerGravity` on a new player will return the wrong value, where that should really be possible.

**Comment by vedran77** [comment]
I don't know how to reproduce that issue. Here are the things I did:

- Created two commands:
```
YCMD:getgravity(playerid, params[], help) {
    printf("playerid %d - gravity %f", playerid, GetPlayerGravity(playerid));
    return 1;
}

YCMD:setgravity(playerid, params[], help) {
    SetPlayerGravity(playerid, 0.044);
    return 1;
}
```
- Set gravity to 0.01 in my config.json.
- When the player with ID 0 initially connected, they received gravity set to 0.01.
- Then, ID 0 executed the command /setgravity and got gravity set to 0.044.
- After that, ID 1 joined the server and executed the command /getgravity, but the result was 0.01.

What did I miss?

**Review by Hual — APPROVED** [review]

**Comment by Hual** [comment]
You didn't miss anything - the gravity is already set to the config one in onPeerConnect()

**Pull request merged**
