### PR TITLE
fix return 130 rpc, if player have a bad name

### PR DESCRIPTION
**Pull request by atomlin-git**
fix issue #738

### CODE REVIEW

**Review by Hual — DISMISSED** [review]

**Comment by Hual** [comment]
While this change makes sense I don't see how it would actually fix the linked issue

**Comment by atomlin-git** [comment]
RPC simply does not have time to reach the player

With out changes: 
image

With changes:
image

**Comment by Hual** [comment]
> RPC simply does not have time to reach the player
> 
> With out changes: image
> 
> With changes: image

But isn't the player being kicked right after that in another function?

**Comment by atomlin-git** [comment]
More better solution in #906

**Pull request closed without merging**
