### PR TITLE
Validate camera modes better

### LINKED ISSUE #873: Improve camera mode validation
Now camera modes are validated this way:
https://github.com/openmultiplayer/open.mp/blob/62a2fa95b36b73640a5b4bb330a1663d6d50adc9/Server/Source/player_pool.hpp#L867-L869

But:
1. It should firstly consider that it's in range of [0..65](https://gtaundergroundmod.com/pages/ug-mp/documentation/camera/modes)
2. The list of surely invalid camera modes related to aiming (so they could cause the same artifacts like derpcam and others) can be extended with 5, 39, 40, 43 and 52 values

### PR DESCRIPTION
**Pull request by NexiusTailer**
This fixes #873 and now it:
* Considers that it's in range of 0..65 of all possible valid camera modes
* Checks **all** invalid camera modes related to aiming

### CODE REVIEW

**Comment by uifdev** [comment]
Why not _only_ allow camera modes that are actually used by the game?

**Comment by NexiusTailer** [comment]
Some may be used by other platforms. For example, camera mode 34 is not used by PC version of GTA SA, but it's generally valid and used by android clients.

**Review by AmyrAhmady — APPROVED** [review]

**Comment by karawangputra379-star** [comment]
Pppppppp

**Comment by karawangputra379-star** [comment]
Hhhad datag red qd, wxfe rv ev

**Pull request merged**
